insert into clubs(name) values
    ('Ale & Lager Enthusiasts of Saskatchewan - ALES'),
    ('Beershack'),
    ('Biergotter'),
    ('Brew Ste Marie'),
    ('Brewnosers'),
    ('BrewVIC'),
    ('Canadian Amateur Brewers Association - CABA'),
    ('Cowtown Yeast Wranglers'),
    ('Durham Homebrewers Club'),
    ('Edmonton Homebrewers Guild'),
    ('Fredricton Craft Brewers Association'),
    ('GTA Brews'),
    ('Lethbridge Werthogs'),
    ('London Homebrewers Guild'),
    ('Members of Barleyment'),
    ('MontreAlers'),
    ('OkBrewers'),
    ('River City of Manitoba Brewers'),
    ('Saskatoon Headhunters'),
    ('Southern Ontario Brewers'),
    ('Toronto Brewers'),
    ('Toronto Brewing'),
    ('VanBrewers'),
    ('Winnipeg Brew Bombers'),
    ('Winnipeg Elite Brewers');
